### ISSUE TITLE
[App Request] AMP -Cubecoders Application Management Panel

### ISSUE THREAD

**Issue by tantgron1337** [WisdomSky/CasaOS-Coolstore#3]
### Brief Description:

AMP (Application Management Panel) is a simple to use, easy to install, self-hosted control panel and management system for hosting game servers.

### Project URL:

https://cubecoders.com/AMP

### Additional Information:

I have tried to get this installed with MitchTalmadge docker version and instructions, but I'm not skilled enough. https://github.com/MitchTalmadge/AMP-dockerized

### Screenshots:

https://www.inmotionhosting.com/support/wp-content/uploads/2022/12/minecraft-amp-update-update-now.png

So greatful if I could get help with this to work, my kid and his friends want there own servers for Terraria. :)

Thank You for the great work with CasaOS and Zimaboard!!

**Comment by WisdomSky** [comment]
Hello, I'm sorry but I think I will not be able to add this one. 
As per the documentation a License is required to run AMP.

But that said, looking at the documentation, setting up the docker container is straight-forward enough.

You can try running the following docker-compose config manually using `docker compose up` command:

#### docker-compose.yaml
```yaml 
services:
  amp:
    image: ghcr.io/imagegenius/amp:latest
    container_name: amp
    mac_address: 02:42:AC:E9:D7:65
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USERNAME=admin
      - PASSWORD=admin
      - LICENCE=00000000-0000-0000-0000-000000000000
    restart: unless-stopped
```
Note: be sure to replace the `LICENSE` with your copy of license and change the `USERNAME` and `PASSWORD` if you prefer having login credentials other than `admin` and `admin`.

The WebUI is accessible through port `8080`


The image used is also from an another maintainer which is actively maintained. The one you linked is somehow inactive for over a year now. 

https://github.com/imagegenius/docker-amp
